from enum import Enum


class CurrencyCode(Enum):
    USD = 1  # US Dollar
    GBP = 2  # British Pound
    EUR = 3  # Euro
    CHF = 4  # Swiss Franc
    RUB = 5  # Russian Rouble
    PLN = 6  # Polish Zloty
    BRL = 7  # Brazilian Real
    JPY = 8  # Japanese Yen
    NOK = 9  # Norwegian Krone
    IDR = 10  # Indonesian Rupiah
    MYR = 11  # Malaysian Ringgit
    PHP = 12  # Philippine Peso
    SGD = 13  # Singapore Dollar
    THB = 14  # Thai Baht
    VND = 15  # Vietnamese Dong
    KRW = 16  # South Korean Won
    TRY = 17  # Turkish Lira
    UAH = 18  # Ukrainian Hryvnia
    MXN = 19  # Mexican Peso
    CAD = 20  # Canadian Dollar
    AUD = 21  # Australian Dollar
    NZD = 22  # New Zealand Dollar
    CNY = 23  # Chinese Renminbi
    INR = 24  # Indian Rupee
    CLP = 25  # Chilean Peso
    PEN = 26  # Peruvian Sol
    COP = 27  # Colombian Peso
    ZAR = 28  # South African Rand
    HKD = 29  # Hong Kong Dollar
    TWD = 30  # New Taiwan Dollar
    SAR = 31  # Saudi Riyal
    AED = 32  # UAE Dirham
    SEK = 33  # Swedish Krona
    ARS = 34  # Argentine Peso
    ILS = 35  # Israeli New Shekel
    BYN = 36  # Belarusian Ruble
    KZT = 37  # Kazakhstani Tenge
    KWD = 38  # Kuwaiti Dinar
    QAR = 39  # Qatari Riyal
    CRC = 40  # Costa Rican Colón
    UYU = 41  # Uruguayan Peso
    BGN = 42  # Bulgarian Lev
    HRK = 43  # Croatian Kuna
    CZK = 44  # Czech Koruna
    DKK = 45  # Danish Krone
    HUF = 46  # Hungarian Forint
    RON = 47  # Romanian Leu